entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs: [${TRUSTED_IPS}]
      insecure: true

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true
  insecure: true
